//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oshyn.Ayudame.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AyudameDbEntities : DbContext
    {
        public AyudameDbEntities()
            : base("name=AyudameDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ElementCatalog> ElementCatalogs { get; set; }
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<MobileUser> MobileUsers { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<StateHistory> StateHistories { get; set; }
    }
}
