//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oshyn.Ayudame.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Element()
        {
            this.StateHistories = new HashSet<StateHistory>();
        }
    
        public long Id { get; set; }
        public int RequestId { get; set; }
        public int CurrentState { get; set; }
        public string Other { get; set; }
        public int ElementCatalogId { get; set; }
        public string Description { get; set; }
    
        public virtual ElementCatalog ElementCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateHistory> StateHistories { get; set; }
        public virtual Request Request { get; set; }
    }
}
