//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oshyn.Ayudame.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geolocation { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
        public int MobileUserId { get; set; }
        public string Title { get; set; }
    
        public virtual MobileUser MobileUser { get; set; }
    }
}
